# Generated by Django 2.2.4 on 2021-03-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=30)),
                ('camera_id', models.PositiveIntegerField()),
                ('direction_id1', models.PositiveIntegerField()),
                ('direction_name1', models.CharField(max_length=30)),
                ('direction_coordinates1', models.FloatField(max_length=30)),
                ('direction_id2', models.PositiveIntegerField()),
                ('direction_name2', models.CharField(max_length=30)),
                ('direction_coordinates2', models.FloatField(max_length=30)),
                ('direction_id3', models.PositiveIntegerField()),
                ('direction_name3', models.CharField(max_length=30)),
                ('direction_coordinates3', models.FloatField(max_length=30)),
                ('direction_id4', models.PositiveIntegerField()),
                ('direction_name4', models.CharField(max_length=30)),
                ('direction_coordinates4', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputName', models.CharField(max_length=200)),
                ('initialTime', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
